name: Build and deploy jobs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, then build the project
        run: |
          npm install
          npm run build
      - name: zip the project
        run: |
          tar -cvf dist
      - name: export the project
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist.tar
  deploy:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Download previous artifact
          uses: actions/download-artifact@v4
          with:
            name: dist.tar
        - name: Upload it on github pages
          uses: actions/deploy-pages@v4
