name: Test, build and deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, then run unit tests
        run: |
          npm install
          npm run test:unit
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, then build the project
        run: |
          npm install
          npm run build
      - name: tar the project
        run: |
          tar -cvf dist.tar dist/*
      - name: gzip the tar file
        run: |
          gzip dist.tar dist.tgz
      - name: upload pages artifacts
        uses: actions/upload-pages-artifact
        with:
          name: github-pages
          path: dist.tgz
  deploy:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Upload it on github pages
          uses: actions/deploy-pages@v4
